baseURL = "https://medicalwei.github.io/debconf18-landing/"
languageCode = "en-us"
title = "DebConf18"
theme = "ananke"
publishDir = "docs"

defaultContentLanguage = "en"

[params]
navigationlogo = "images/navigation_logo.svg"

[menu]
  [[menu.main]]
  identifier = "home"
  name       = "Home"
  url        = "/"
  weight     = 1


[languages]
  [languages.en]
  weight = 1
  languageName = "English"

    [[languages.en.menu.main]]
    url    = "/"
    name   = "Home"
    weight = 1

    [[languages.en.menu.main]]
    name   = "About"
    url    = "/about"
    weight = 2
    
    [[languages.en.menu.main]]
    name   = "Sponsors"
    url    = "/sponsors"
    weight = 3
    
    [[languages.en.menu.main]]
    name   = "CfP"
    url    = "/cfp"
    weight = 4
    
    [[languages.en.menu.main]]
    name   = "中文"
    title  = "切換至中文頁面"
    url    = "/zh-hant-tw/"
    weight = 100

  [languages.zh-hant-tw]
  languageCode = "zh-hant-tw"
  weight = 2

    [[languages.zh-hant-tw.menu.main]]
    url    = "/zh-hant-tw/"
    name   = "首頁"
    weight = 1

    [[languages.zh-hant-tw.menu.main]]
    name   = "關於"
    url    = "/zh-hant-tw/about"
    weight = 2
    
    [[languages.zh-hant-tw.menu.main]]
    name   = "Sponsors"
    url    = "/zh-hant-tw/sponsors"
    weight = 3

    [[languages.zh-hant-tw.menu.main]]
    name   = "CfP"
    url    = "/zh-hant-tw/cfp"
    weight = 4

    [[languages.zh-hant-tw.menu.main]]
    name   = "English"
    url    = "/"
    weight = 100
